import type { NextPage } from "next";
import Head from "next/head";

import { LinkButton, SiteHeader, SiteSider, VercelLogo } from "@components";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader />
      <div className="flex flex-col h-full pt-12 justify-start items-center">
        {/* <SiteSider /> */}
        <main className=" pb-32">
          <header className="flex flex-col items-center space-y-12">
            <h1 className="m-7 text-5xl text-grey-700">WhpptJS</h1>
            <p className=" max-w-xl text-2xl text-grey-600 text-center">
              Extending Nuxt / Next into a full featured CMS framework.
            </p>
            <LinkButton
              href="/guide/gettingStarted/prerequisites.html"
              className="bg-grey-700 text-white rounded hover:text-white hover:bg-grey-600 p-4"
            >
              Get Started →
            </LinkButton>
          </header>
        </main>
        <VercelLogo />
      </div>
    </div>
  );
};

export default Home;
